env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - standard
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  {
    'no-use-before-define': [0],
    '@typescript-eslint/no-use-before-define': [1],
  }
